Configure some code quality diagnostics (IDExxxx) as warnings
DotNetAnalyzers/StyleCopAnalyzers pull request #3501
Opened 2022-05-07 12:09 UTC by bjornhellander

I have gotten comments on pull requests regarding unnecessary using statements, so I thought it would be better to configure it as a warning instead, so it is caught automatically. Also did the same with some more IDE diagnostics that I think will be uncontroversial and had violations in the repository.

2022-05-09 15:04 UTC, sharwell requested changes

2022-05-09 15:04 UTC, sharwell commented on .editorconfig
> +dotnet_diagnostic.IDE0005.severity = warning      # Remove unnecessary import
According to EditorConfig.org, placement of a "comment" at the end of a line has unspecified behavior. Comments should always precede the configuration in this file.

2022-05-09 19:15 UTC, bjornhellander commented on StyleCop.Analyzers/StyleCop.Analyzers/Settings/SettingsHelper.cs
> -        private static SourceTextValueProvider<StyleCopSettings> SettingsValueProvider { get; } =
Looks like commit b5228ba9d8a1ac9aa3e16120a7d48ce2c1d29782

2022-05-09 19:41 UTC, sharwell commented on StyleCop.Analyzers/StyleCop.Analyzers/Settings/SettingsHelper.cs
> -        private static SourceTextValueProvider<StyleCopSettings> SettingsValueProvider { get; } =
No, seems fine. Previously all syntax trees in a compilation had the same `StyleCopSettings`, but with **.editorconfig** it's possible for options to vary.

2022-05-10 19:18 UTC, bjornhellander commented on .editorconfig
> +dotnet_diagnostic.IDE0005.severity = warning      # Remove unnecessary import
Sure. Are you interested in the three other diagnostics, provided they are configured in the ruleset files instead?

2022-05-28 16:51 UTC, closed without merging