Update SA1402 to handle records and record structs
DotNetAnalyzers/StyleCopAnalyzers pull request #3570
Opened 2022-10-23 13:06 UTC by bjornhellander

Fixes #3542

2022-10-23 17:19 UTC, bjornhellander commented
Ready for review

2022-10-23 17:19 UTC, bjornhellander commented
Note that I did not add any tests for `record class`, since there is no new syntax node for it. Let me know if tests are still expected.

2022-12-03 10:27 UTC, bjornhellander commented
Can you take a look at this, @sharwell?

2023-01-21 14:10 UTC, bjornhellander commented
@sharwell?

2023-02-09 19:25 UTC, sharwell requested changes
Marking request changes to get the updates mentioned in comments.

2023-02-10 07:19 UTC, bjornhellander commented on StyleCop.Analyzers/StyleCop.Analyzers.Test.CSharp10/MaintainabilityRules/SA1402CSharp10ForRecordStructUnitTests.cs
> +#nullable disable
Remove it

2023-02-10 07:19 UTC, bjornhellander commented on StyleCop.Analyzers/StyleCop.Analyzers.Test.CSharp10/MaintainabilityRules/SA1402CSharp10ForRecordStructUnitTests.cs
> +    public class SA1402CSharp10ForRecordStructUnitTests : SA1402ForBlockDeclarationUnitTestsBase
Added tests

2023-02-10 14:28 UTC, sharwell approved these changes

2023-02-10 14:29 UTC, merged